/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package jframes;

/**
 *
 * @author Farmácia
 */
public class TelaRegistrarMoto extends javax.swing.JPanel {

    /**
     * Creates new form TelaRegistrarMoto
     */
    public TelaRegistrarMoto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PlacaCarro = new javax.swing.JTextField();
        CambioCarro = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        Ok = new javax.swing.JButton();
        CombuCarro = new javax.swing.JTextField();
        lbCancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        PortasCarro = new javax.swing.JComboBox<>();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jLabel7 = new javax.swing.JLabel();
        PortaMaCarro = new javax.swing.JTextField();
        ArCarro = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        NomeCarro = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        MarcaCarro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ModeloCarro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        AnoCarro = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        PlacaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlacaCarroActionPerformed(evt);
            }
        });

        CambioCarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Automatico" }));

        jLabel6.setText("Portas:");

        Ok.setText("OK");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });

        CombuCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CombuCarroActionPerformed(evt);
            }
        });

        lbCancel.setText("Cancelar");
        lbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lbCancelActionPerformed(evt);
            }
        });

        jLabel8.setText("Combustivel:");

        PortasCarro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "4 Portas", "2 Portas" }));
        PortasCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortasCarroActionPerformed(evt);
            }
        });

        jDesktopPane1.setBackground(new java.awt.Color(242, 242, 242));

        jLabel7.setText("Capacidade Porta malas (L):");

        PortaMaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PortaMaCarroActionPerformed(evt);
            }
        });

        jDesktopPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(PortaMaCarro, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(159, 159, 159)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PortaMaCarro)
                .addGap(123, 123, 123))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(PortaMaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3))
        );

        ArCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ArCarroActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome:");

        NomeCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeCarroActionPerformed(evt);
            }
        });

        jLabel2.setText("Marca:");

        MarcaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MarcaCarroActionPerformed(evt);
            }
        });

        jLabel3.setText("Modelo:");

        ModeloCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModeloCarroActionPerformed(evt);
            }
        });

        jLabel4.setText("Ano:");

        AnoCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnoCarroActionPerformed(evt);
            }
        });

        jLabel10.setText("Ar Condicionado:");

        jLabel5.setText("Placa:");

        jLabel11.setText("Cambio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AnoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(PlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(NomeCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(MarcaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CombuCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ArCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CambioCarro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel3))
                                .addGap(4, 4, 4)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(ModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(PortasCarro, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCancel))
                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(NomeCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(MarcaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(ModeloCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(AnoCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(PlacaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(PortasCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(CombuCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(ArCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(CambioCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCancel)
                    .addComponent(Ok))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void PlacaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlacaCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PlacaCarroActionPerformed

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
        Nome = (String) NomeCarro.getText();
        Marca = (String) MarcaCarro.getText();
        Modelo = (String) ModeloCarro.getText();
        Ano = (String) AnoCarro.getText();
        Placa = (String) PlacaCarro.getText();
        Portas = (String) PortasCarro.getSelectedItem();
        Combus = (String) CombuCarro.getText();
        Ar = (String) ArCarro.getText();
        Cambio = (String) CambioCarro.getSelectedItem();
        CapPoMa = (String) PortaMaCarro.getText();
        this.dispose();
    }//GEN-LAST:event_OkActionPerformed

    private void CombuCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CombuCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CombuCarroActionPerformed

    private void lbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lbCancelActionPerformed
        Nome = null;
        Marca = null;
        Modelo = null;
        Ano = null;
        Placa = null;
        Portas = null;
        Combus = null;
        Ar = null;
        Cambio = null;
        CapPoMa = null;
        this.dispose();

    }//GEN-LAST:event_lbCancelActionPerformed

    private void PortasCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortasCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PortasCarroActionPerformed

    private void PortaMaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PortaMaCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PortaMaCarroActionPerformed

    private void ArCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ArCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ArCarroActionPerformed

    private void NomeCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NomeCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NomeCarroActionPerformed

    private void MarcaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MarcaCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MarcaCarroActionPerformed

    private void ModeloCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModeloCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModeloCarroActionPerformed

    private void AnoCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnoCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnoCarroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AnoCarro;
    private javax.swing.JTextField ArCarro;
    private javax.swing.JComboBox<String> CambioCarro;
    private javax.swing.JTextField CombuCarro;
    private javax.swing.JTextField MarcaCarro;
    private javax.swing.JTextField ModeloCarro;
    private javax.swing.JTextField NomeCarro;
    private javax.swing.JButton Ok;
    private javax.swing.JTextField PlacaCarro;
    private javax.swing.JTextField PortaMaCarro;
    private javax.swing.JComboBox<String> PortasCarro;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JButton lbCancel;
    // End of variables declaration//GEN-END:variables
}
