/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jframes;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import veiculos.*;

public class TelaListaVeiculos extends javax.swing.JFrame {
    private List<Car> carrocerto;
     private List<Moto> motocerto;
    private String EscolhaStringCar;
    
    public void setListCar(List<Car> carrocerto){
    this.carrocerto = carrocerto;
   
        
    }
    public void setListmoto(List<Moto> motocerto){
    this.motocerto = motocerto;
    }
    
    public String getEscolhaStringCar(){
        return this.EscolhaStringCar;
    }

    
    public TelaListaVeiculos() {
        initComponents();
        setLocationRelativeTo(null);
    }
    public void preencherListaCar() {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < carrocerto.size(); i++) {
            Veiculo veiculogamer = carrocerto.get(i);
            sb.append(i + 1).append(". ")
              .append(veiculogamer.getNome()).append(" - ")
              .append(veiculogamer.getPlaca()).append(" - Ano: ")
              .append(veiculogamer.getAno()).append("\n");
        }
        listaCarros.setText(sb.toString());
    }
    public void preencherListaMoto() {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < motocerto.size(); i++) {
            Veiculo veiculogamer = motocerto.get(i);
            sb.append(i + 1).append(". ")
              .append(veiculogamer.getNome()).append(" - ")
              .append(veiculogamer.getPlaca()).append(" - Ano: ")
                    .append(veiculogamer.getAno()).append("\n");
        }
        listaCarros.setText(sb.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listaCarros = new javax.swing.JTextArea();
        OkverCarro = new javax.swing.JButton();
        CancelVerCarro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        TextoEscolhaCarro = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lista de veiculos");

        listaCarros.setEditable(false);
        listaCarros.setColumns(20);
        listaCarros.setRows(5);
        jScrollPane1.setViewportView(listaCarros);

        OkverCarro.setText("OK");
        OkverCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkverCarroActionPerformed(evt);
            }
        });

        CancelVerCarro.setText("Cancelar");
        CancelVerCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelVerCarroActionPerformed(evt);
            }
        });

        jLabel1.setText("Digite o numero do Veiculo para selecionar:");

        TextoEscolhaCarro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextoEscolhaCarroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 225, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OkverCarro, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CancelVerCarro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TextoEscolhaCarro))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TextoEscolhaCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelVerCarro)
                    .addComponent(OkverCarro))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TextoEscolhaCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextoEscolhaCarroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextoEscolhaCarroActionPerformed

    private void CancelVerCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelVerCarroActionPerformed
        TextoEscolhaCarro = null;
        this.dispose();
    }//GEN-LAST:event_CancelVerCarroActionPerformed

    private void OkverCarroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkverCarroActionPerformed
        EscolhaStringCar = (String) TextoEscolhaCarro.getText();
        this.dispose();
    }//GEN-LAST:event_OkverCarroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaListaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaListaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaListaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaListaVeiculos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaListaVeiculos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelVerCarro;
    private javax.swing.JButton OkverCarro;
    private javax.swing.JTextField TextoEscolhaCarro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea listaCarros;
    // End of variables declaration//GEN-END:variables
}
